# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='compositions',
            field=models.ManyToManyField(blank=True, help_text='Composition', null=True, through='carte.Composition', to='carte.Composant'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='images',
            field=models.ManyToManyField(blank=True, help_text="Pictogramme d'information", null=True, to='carte.TissuImage'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='largeur',
            field=models.FloatField(blank=True, help_text='Largeur', null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='raccord',
            field=models.FloatField(blank=True, help_text='Raccord', null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='utilisation',
            field=models.ManyToManyField(blank=True, help_text='Utilisation', null=True, to='carte.Utilisation'),
        ),
    ]
