# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_auto_20170227_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=120, null=True),
        ),
    ]
