# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Référence', max_length=75, unique=True)),
                ('largeur', models.FloatField(help_text='Largeur')),
                ('raccord', models.FloatField(help_text='Raccord')),
            ],
        ),
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du composant', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.FloatField(help_text='Pourcentage du composant dansle tissu')),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Carte')),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Composant')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la marque', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TissuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'image", max_length=75)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'utilisation", max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='carte',
            name='compositions',
            field=models.ManyToManyField(help_text='Composition', through='carte.Composition', to='carte.Composant'),
        ),
        migrations.AddField(
            model_name='carte',
            name='images',
            field=models.ManyToManyField(help_text="Pictogramme d'information", to='carte.TissuImage'),
        ),
        migrations.AddField(
            model_name='carte',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.Marque'),
        ),
        migrations.AddField(
            model_name='carte',
            name='utilisation',
            field=models.ManyToManyField(help_text='Utilisation', to='carte.Utilisation'),
        ),
    ]
